android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
org.gradle.daemon=true
org.gradle.jvmargs=-Xmx6144m -Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.caching=true
org.gradle.workers.max=2
org.gradle.configuration-cache=true
RELEASE_STORE_FILE=D\:\\private work\\aquamemo.jks
RELEASE_STORE_PASSWORD=vDTLIw%ME#qZpk!9
RELEASE_KEY_ALIAS=key0
RELEASE_KEY_PASSWORD=B(TyG*AHECx%zfsk
systemProp.java.net.preferIPv4Stack=true
android.disallowKotlinSourceSets=false
systemProp.sun.net.client.defaultConnectTimeout=120000
systemProp.sun.net.client.defaultReadTimeout=120000